# Coins plugin by: Beelzebu
# If you need support or find a bug open a issuse in
# the official github repo https://github.com/Beelzebu/Coins/issues/

# The version of the config, don't touch!
version: 10

# This is the prefix used in all the messages.
Prefix: '&c&lCoins &6&l>&7'

# Set this to true to use the player uuid or set to false to use player name.
Online Mode: true

# Here you can enable Vault to make this plugin manage all the Vault transactions.
Vault:
  Use: false
  # Names used by vault for the currency.
  Name:
    Singular: 'Coin'
    Plural: 'Coins'

# Here are the MySQL server settings.
MySQL:
  Use: false
  Host: 'localhost'
  Port: '3306'
  Database: 'minecraft'
  User: 'root'
  Password: 'S3CUR3P4SSW0RD'
  Prefix: 'Coins_'
  Connection Interval: 5

# Plugin general configurations.
General:
  # Here you can define the starting coins of a player when is registred in the
  # database or his coins are reset with "/coins reset"
  Starting Coins: 0
  # Here you can configure the base command of the plugin.
  Command:
    Name: 'coins'
    Description: 'Base command of the Coins plugin'
    Usage: '/coins'
    Permission: 'coins.use'
    Aliases:
    - 'mycoins'
    - 'coinsalias'
  # Here you can configure the autopurge of inactive accounts.
  Purge:
    Enabled: true # If this is true the old accouns would be purged at server startup.
    Days: 60 # The time in days before deleting an account.
    Logs:
      Days: 10 # The days to keep plugin logs.
  Executor Sign:
    '1': '&c&lCoins'
    '2': '%executor_displayname%'
    '3': '%ececutor_cost%'
    '4': ''

# Here you can define a cost to use a specific command.
Command Cost:
  /example: 100.0 # When a player use this command, we gonna take 100 coins from his account.
  /command: 5.5 # You can use decimals too.

# Here you can make that coins run a command from the console and take a cost to the user.
Command executor:
  # This is the command name to use in /coins execute
  # This is useful if you want to give things to the players by coins.
  # With the command below you should use /coins execute example1
  example1:
    # This is the command that the console gonna run.
    Command: 
    - 'eco give %player% 10000' # Note the %player% placeholder, this is replaced by the player that runs the command.
    Cost: 100 # This is the cost of the command.
  '2':
    # You can create executors without cost.
    Command: 
    - 'broadcast: %player% Is awesome!'
  list:
    # You can also create a list of commands to run when the executor is called.
    Command:
    - 'kill %player%'
    - 'msg %player% we''re sorry :('
  all:
    # There are some special types of commands to execute: "message:" and "broadcast:"
    # The "message:" command send the message after the ":" to the player.
    # The "broadcast:" command broadcast a message to the server.
    Command:
    - 'message: You win 100 $'
    - 'broadcast: %player% winned 100 $'
    - 'eco give %player% 100'
    Cost: 10
  # This example executor is to be used with signs, for signs you can add the 'Displayname'
  # to be used in the sign, if isn't present the id is used for the displayname, in this case
  # if we don't put the Displayname this would be: sign1
  sign1:
    Displayname: '&lNormal Key'
    Command:
    - 'crate givekey %player% 1 normal'
    - 'message:Here are your key!'
    Cost: 2
Multipliers:
  # Here you can configure some aspects of the GUI of multipliers
  GUI:
    Close:
      # If you're using 1.8 please check http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
      # If you're using 1.9+ use https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
      Sound: 'UI_BUTTON_CLICK'
      Pitch: '1'
    Use:
      Sound: 'ENTITY_PLAYER_LEVELUP'
      Pitch: '2'
      Fail:
        Sound: 'ENTITY_VILLAGER_NO'
        Pitch: '1'
  # This is the server identifier, is used only if you have MySQL enabled, when a player enables a multiplier in
  # this server, this is also enabled in all the other servers that has this identifier.
  Server: 'default'

# This is for enable the debug mode, this gonna send more messages to the console to see what
# is happening with the plugin, please enable this to report bugs.
Debug: false
