# Coins plugin by: Beelzebu
# If you need support or find a bug open a issuse in
# the official github repo https://github.com/Beelzebu/Coins/issues/

# The version of the config, don't touch!
version: 3

# Set this to true to use the player uuid or set to false to use player name.
Online Mode: true

# Here are the MySQL server settings.
MySQL:
  Use: true
  Host: localhost
  Port: 3306
  Database: minecraft
  User: root
  Password: S3CUR3P4SSW0RD
  Prefix: Coins_
  Connection Interval: 5
  
# Here you can configure the base command of the plugin.
Command:
  Name: 'coins'
  Description: 'Base command of the Coins plugin'
  Usage: '/coins'
  Permission: 'coins.use'
  Aliases:
  - 'mycoins'
  - 'coinsalias'

# Here you can define a cost to use a specific command.
Command Cost:
  /example: 100.0 # When a player use this command, we gonna take 100 coins from his account.
  /command: 5.5 # You can use decimals too.
# Here you can make that coins run a command from the console and take a cost to the user.
Command executor:
  # This is the command name to use in /coins execute
  # This is useful if you want to give things to the players by coins.
  # With the command below you should use /coins execute example1
  example1:
    # This is the command that the console gonna run.
    Command: 'eco give %player% 10000' # Note the %player% placeholder, this is replaced by the player that runs the command.
    Cost: 100 # This is the cost of the command.
  # If you are going to put a number, put it with single quotes
  '2':
    Command: 'broadcast %player% Is awesome!'
    Cost: 1
Multipliers:
  # This is the server identifier, is used only if you have MySQL enabled, when a player enables a multiplier in
  # this server, this is also enabled in all the other servers that has this identifier.
  Server: 'default'
  Amount: 1
# This is for enable the debug mode, this gonna send more messages to the console to see what
# is happening with the plugin, please enable this to report bugs.
Debug: false