# Coins plugin by: Beelzebu
# If you need support or find a bug open a issuse in
# the official github repo https://github.com/Beelzebu/Coins/issuses/

# The version of the config, don't touch!
version: 1

# Set this to true to use the player uuid or set to false to use player name.
Online Mode: true

# Here are the MySQL server settings.
MySQL:
  Host: localhost
  Port: 3306
  Database: minecraft
  User: root
  Password: S3CUR3P4SSW0RD
  Prefix: Coins_
  Connection Interval: 5

# Here you can define a cost to use a specific command.
Command Cost:
  /example: 100.0 # When a player use this command, we gonna take 100 coins from his account.
  /command: 5.5 # You can use decimals too.
# Here you can make that coins run a command from the console and take a cost to the user.
Command executor:
  # This is the command name to use in /coins execute
  # This is useful if you want to give things to the players by coins.
  # With the command below you should use /coins execute example1
  example1:
    # This is the command that the console gonna run.
    Command: 'eco give %player% 10000' # Note the %player% placeholder, this is replaced by the player that runs the command.
    Cost: 100 # This is the cost of the command.
  # If you are going to put a number, put it in single quotes
  '2':
    Command: 'broadcast %player% Is awesome!'
    Cost: 1
Multipliers:
  Amount: 1
  Enabler: ''