name: ${project.artifactId}
load: STARTUP
loadbefore: [Vault]
softdepend: [PlaceholderAPI, Vault, LeaderHeads]
main: ${project.groupId}.coins.bukkit.Main
version: ${project.version}
author: Beelzebu
website: https://www.spigotmc.org/resources/48536/